//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TypescriptParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITypescriptParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class TypescriptParserBaseListener : ITypescriptParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.compilation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilation_unit([NotNull] TypescriptParser.Compilation_unitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.compilation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilation_unit([NotNull] TypescriptParser.Compilation_unitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.namespace_or_type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_or_type_name([NotNull] TypescriptParser.Namespace_or_type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.namespace_or_type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_or_type_name([NotNull] TypescriptParser.Namespace_or_type_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] TypescriptParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] TypescriptParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.base_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase_type([NotNull] TypescriptParser.Base_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.base_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase_type([NotNull] TypescriptParser.Base_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.simple_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_type([NotNull] TypescriptParser.Simple_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.simple_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_type([NotNull] TypescriptParser.Simple_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.numeric_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeric_type([NotNull] TypescriptParser.Numeric_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.numeric_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeric_type([NotNull] TypescriptParser.Numeric_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.class_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_type([NotNull] TypescriptParser.Class_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.class_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_type([NotNull] TypescriptParser.Class_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.type_argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_argument_list([NotNull] TypescriptParser.Type_argument_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.type_argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_argument_list([NotNull] TypescriptParser.Type_argument_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_list([NotNull] TypescriptParser.Argument_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_list([NotNull] TypescriptParser.Argument_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] TypescriptParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] TypescriptParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] TypescriptParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] TypescriptParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.non_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNon_assignment_expression([NotNull] TypescriptParser.Non_assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.non_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNon_assignment_expression([NotNull] TypescriptParser.Non_assignment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] TypescriptParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] TypescriptParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] TypescriptParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] TypescriptParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_expression([NotNull] TypescriptParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_expression([NotNull] TypescriptParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.conditional_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_or_expression([NotNull] TypescriptParser.Conditional_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.conditional_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_or_expression([NotNull] TypescriptParser.Conditional_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.conditional_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_and_expression([NotNull] TypescriptParser.Conditional_and_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.conditional_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_and_expression([NotNull] TypescriptParser.Conditional_and_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusive_or_expression([NotNull] TypescriptParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusive_or_expression([NotNull] TypescriptParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusive_or_expression([NotNull] TypescriptParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusive_or_expression([NotNull] TypescriptParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expression([NotNull] TypescriptParser.And_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expression([NotNull] TypescriptParser.And_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality_expression([NotNull] TypescriptParser.Equality_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality_expression([NotNull] TypescriptParser.Equality_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelational_expression([NotNull] TypescriptParser.Relational_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelational_expression([NotNull] TypescriptParser.Relational_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expression([NotNull] TypescriptParser.Shift_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expression([NotNull] TypescriptParser.Shift_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditive_expression([NotNull] TypescriptParser.Additive_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditive_expression([NotNull] TypescriptParser.Additive_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicative_expression([NotNull] TypescriptParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicative_expression([NotNull] TypescriptParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] TypescriptParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] TypescriptParser.Unary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression([NotNull] TypescriptParser.Primary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression([NotNull] TypescriptParser.Primary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpression([NotNull] TypescriptParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpression([NotNull] TypescriptParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>simpleNameExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleNameExpression([NotNull] TypescriptParser.SimpleNameExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>simpleNameExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleNameExpression([NotNull] TypescriptParser.SimpleNameExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesisExpressions</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesisExpressions([NotNull] TypescriptParser.ParenthesisExpressionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesisExpressions</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesisExpressions([NotNull] TypescriptParser.ParenthesisExpressionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>literalAccessExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralAccessExpression([NotNull] TypescriptParser.LiteralAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>literalAccessExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralAccessExpression([NotNull] TypescriptParser.LiteralAccessExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>thisReferenceExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThisReferenceExpression([NotNull] TypescriptParser.ThisReferenceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>thisReferenceExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThisReferenceExpression([NotNull] TypescriptParser.ThisReferenceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>objectCreationExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectCreationExpression([NotNull] TypescriptParser.ObjectCreationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>objectCreationExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectCreationExpression([NotNull] TypescriptParser.ObjectCreationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_access([NotNull] TypescriptParser.Member_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_access([NotNull] TypescriptParser.Member_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.bracket_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracket_expression([NotNull] TypescriptParser.Bracket_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.bracket_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracket_expression([NotNull] TypescriptParser.Bracket_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.lambda_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambda_expression([NotNull] TypescriptParser.Lambda_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.lambda_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambda_expression([NotNull] TypescriptParser.Lambda_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.anonymous_function_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonymous_function_signature([NotNull] TypescriptParser.Anonymous_function_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.anonymous_function_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonymous_function_signature([NotNull] TypescriptParser.Anonymous_function_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.explicit_anonymous_function_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicit_anonymous_function_parameter_list([NotNull] TypescriptParser.Explicit_anonymous_function_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.explicit_anonymous_function_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicit_anonymous_function_parameter_list([NotNull] TypescriptParser.Explicit_anonymous_function_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.explicit_anonymous_function_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicit_anonymous_function_parameter([NotNull] TypescriptParser.Explicit_anonymous_function_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.explicit_anonymous_function_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicit_anonymous_function_parameter([NotNull] TypescriptParser.Explicit_anonymous_function_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.implicit_anonymous_function_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicit_anonymous_function_parameter_list([NotNull] TypescriptParser.Implicit_anonymous_function_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.implicit_anonymous_function_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicit_anonymous_function_parameter_list([NotNull] TypescriptParser.Implicit_anonymous_function_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.anonymous_function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonymous_function_body([NotNull] TypescriptParser.Anonymous_function_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.anonymous_function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonymous_function_body([NotNull] TypescriptParser.Anonymous_function_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>declarationStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationStatement([NotNull] TypescriptParser.DeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>declarationStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationStatement([NotNull] TypescriptParser.DeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>embeddedStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmbeddedStatement([NotNull] TypescriptParser.EmbeddedStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>embeddedStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmbeddedStatement([NotNull] TypescriptParser.EmbeddedStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmbedded_statement([NotNull] TypescriptParser.Embedded_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmbedded_statement([NotNull] TypescriptParser.Embedded_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>emptyStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement([NotNull] TypescriptParser.EmptyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>emptyStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement([NotNull] TypescriptParser.EmptyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expressionStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] TypescriptParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expressionStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] TypescriptParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] TypescriptParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] TypescriptParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>switchStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] TypescriptParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>switchStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] TypescriptParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>whileStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] TypescriptParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>whileStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] TypescriptParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>doStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoStatement([NotNull] TypescriptParser.DoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>doStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoStatement([NotNull] TypescriptParser.DoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>forStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] TypescriptParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] TypescriptParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>foreachStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachStatement([NotNull] TypescriptParser.ForeachStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>foreachStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachStatement([NotNull] TypescriptParser.ForeachStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] TypescriptParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] TypescriptParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>continueStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] TypescriptParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>continueStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] TypescriptParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>returnStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] TypescriptParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>returnStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] TypescriptParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>throwStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowStatement([NotNull] TypescriptParser.ThrowStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>throwStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowStatement([NotNull] TypescriptParser.ThrowStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tryStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryStatement([NotNull] TypescriptParser.TryStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tryStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryStatement([NotNull] TypescriptParser.TryStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] TypescriptParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] TypescriptParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.local_variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocal_variable_declaration([NotNull] TypescriptParser.Local_variable_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.local_variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocal_variable_declaration([NotNull] TypescriptParser.Local_variable_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.local_variable_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocal_variable_type([NotNull] TypescriptParser.Local_variable_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.local_variable_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocal_variable_type([NotNull] TypescriptParser.Local_variable_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.local_variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocal_variable_declarator([NotNull] TypescriptParser.Local_variable_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.local_variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocal_variable_declarator([NotNull] TypescriptParser.Local_variable_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.if_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_body([NotNull] TypescriptParser.If_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.if_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_body([NotNull] TypescriptParser.If_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.switch_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_section([NotNull] TypescriptParser.Switch_sectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.switch_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_section([NotNull] TypescriptParser.Switch_sectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.switch_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_label([NotNull] TypescriptParser.Switch_labelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.switch_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_label([NotNull] TypescriptParser.Switch_labelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_list([NotNull] TypescriptParser.Statement_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_list([NotNull] TypescriptParser.Statement_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.for_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_initializer([NotNull] TypescriptParser.For_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.for_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_initializer([NotNull] TypescriptParser.For_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.for_iterator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_iterator([NotNull] TypescriptParser.For_iteratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.for_iterator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_iterator([NotNull] TypescriptParser.For_iteratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.catch_clauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatch_clauses([NotNull] TypescriptParser.Catch_clausesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.catch_clauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatch_clauses([NotNull] TypescriptParser.Catch_clausesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.specific_catch_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecific_catch_clause([NotNull] TypescriptParser.Specific_catch_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.specific_catch_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecific_catch_clause([NotNull] TypescriptParser.Specific_catch_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.general_catch_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneral_catch_clause([NotNull] TypescriptParser.General_catch_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.general_catch_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneral_catch_clause([NotNull] TypescriptParser.General_catch_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.finally_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinally_clause([NotNull] TypescriptParser.Finally_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.finally_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinally_clause([NotNull] TypescriptParser.Finally_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.resource_acquisition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource_acquisition([NotNull] TypescriptParser.Resource_acquisitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.resource_acquisition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource_acquisition([NotNull] TypescriptParser.Resource_acquisitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.namespace_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_declaration([NotNull] TypescriptParser.Namespace_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.namespace_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_declaration([NotNull] TypescriptParser.Namespace_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.namespace_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_body([NotNull] TypescriptParser.Namespace_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.namespace_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_body([NotNull] TypescriptParser.Namespace_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.namespace_member_declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_member_declarations([NotNull] TypescriptParser.Namespace_member_declarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.namespace_member_declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_member_declarations([NotNull] TypescriptParser.Namespace_member_declarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.namespace_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_member_declaration([NotNull] TypescriptParser.Namespace_member_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.namespace_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_member_declaration([NotNull] TypescriptParser.Namespace_member_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.type_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_declaration([NotNull] TypescriptParser.Type_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.type_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_declaration([NotNull] TypescriptParser.Type_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.type_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_parameter_list([NotNull] TypescriptParser.Type_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.type_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_parameter_list([NotNull] TypescriptParser.Type_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.type_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_parameter([NotNull] TypescriptParser.Type_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.type_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_parameter([NotNull] TypescriptParser.Type_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.class_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_body([NotNull] TypescriptParser.Class_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.class_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_body([NotNull] TypescriptParser.Class_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.class_member_declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_member_declarations([NotNull] TypescriptParser.Class_member_declarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.class_member_declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_member_declarations([NotNull] TypescriptParser.Class_member_declarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.class_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_member_declaration([NotNull] TypescriptParser.Class_member_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.class_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_member_declaration([NotNull] TypescriptParser.Class_member_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.all_member_modifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAll_member_modifiers([NotNull] TypescriptParser.All_member_modifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.all_member_modifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAll_member_modifiers([NotNull] TypescriptParser.All_member_modifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.all_member_modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAll_member_modifier([NotNull] TypescriptParser.All_member_modifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.all_member_modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAll_member_modifier([NotNull] TypescriptParser.All_member_modifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.common_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommon_member_declaration([NotNull] TypescriptParser.Common_member_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.common_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommon_member_declaration([NotNull] TypescriptParser.Common_member_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.typed_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTyped_member_declaration([NotNull] TypescriptParser.Typed_member_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.typed_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTyped_member_declaration([NotNull] TypescriptParser.Typed_member_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.variable_declarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declarators([NotNull] TypescriptParser.Variable_declaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.variable_declarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declarators([NotNull] TypescriptParser.Variable_declaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declarator([NotNull] TypescriptParser.Variable_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declarator([NotNull] TypescriptParser.Variable_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.variable_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_initializer([NotNull] TypescriptParser.Variable_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.variable_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_initializer([NotNull] TypescriptParser.Variable_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.return_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_type([NotNull] TypescriptParser.Return_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.return_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_type([NotNull] TypescriptParser.Return_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.member_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_name([NotNull] TypescriptParser.Member_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.member_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_name([NotNull] TypescriptParser.Member_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.method_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_body([NotNull] TypescriptParser.Method_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.method_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_body([NotNull] TypescriptParser.Method_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.formal_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormal_parameter_list([NotNull] TypescriptParser.Formal_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.formal_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormal_parameter_list([NotNull] TypescriptParser.Formal_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.fixed_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixed_parameters([NotNull] TypescriptParser.Fixed_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.fixed_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixed_parameters([NotNull] TypescriptParser.Fixed_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.fixed_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixed_parameter([NotNull] TypescriptParser.Fixed_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.fixed_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixed_parameter([NotNull] TypescriptParser.Fixed_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.constructor_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor_initializer([NotNull] TypescriptParser.Constructor_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.constructor_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor_initializer([NotNull] TypescriptParser.Constructor_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] TypescriptParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] TypescriptParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.variant_type_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariant_type_parameter_list([NotNull] TypescriptParser.Variant_type_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.variant_type_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariant_type_parameter_list([NotNull] TypescriptParser.Variant_type_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.variant_type_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariant_type_parameter([NotNull] TypescriptParser.Variant_type_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.variant_type_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariant_type_parameter([NotNull] TypescriptParser.Variant_type_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.enum_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_body([NotNull] TypescriptParser.Enum_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.enum_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_body([NotNull] TypescriptParser.Enum_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.enum_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_member_declaration([NotNull] TypescriptParser.Enum_member_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.enum_member_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_member_declaration([NotNull] TypescriptParser.Enum_member_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.right_arrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_arrow([NotNull] TypescriptParser.Right_arrowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.right_arrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_arrow([NotNull] TypescriptParser.Right_arrowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.right_shift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_shift([NotNull] TypescriptParser.Right_shiftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.right_shift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_shift([NotNull] TypescriptParser.Right_shiftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.right_shift_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_shift_assignment([NotNull] TypescriptParser.Right_shift_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.right_shift_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_shift_assignment([NotNull] TypescriptParser.Right_shift_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] TypescriptParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] TypescriptParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_literal([NotNull] TypescriptParser.Boolean_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_literal([NotNull] TypescriptParser.Boolean_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_literal([NotNull] TypescriptParser.String_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_literal([NotNull] TypescriptParser.String_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.class_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_definition([NotNull] TypescriptParser.Class_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.class_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_definition([NotNull] TypescriptParser.Class_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.enum_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_definition([NotNull] TypescriptParser.Enum_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.enum_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_definition([NotNull] TypescriptParser.Enum_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.field_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_declaration([NotNull] TypescriptParser.Field_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.field_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_declaration([NotNull] TypescriptParser.Field_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.constructor_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor_declaration([NotNull] TypescriptParser.Constructor_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.constructor_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor_declaration([NotNull] TypescriptParser.Constructor_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_declaration([NotNull] TypescriptParser.Method_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_declaration([NotNull] TypescriptParser.Method_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.method_member_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_member_name([NotNull] TypescriptParser.Method_member_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.method_member_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_member_name([NotNull] TypescriptParser.Method_member_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.arg_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg_declaration([NotNull] TypescriptParser.Arg_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.arg_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg_declaration([NotNull] TypescriptParser.Arg_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.method_invocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_invocation([NotNull] TypescriptParser.Method_invocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.method_invocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_invocation([NotNull] TypescriptParser.Method_invocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.object_creation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_creation_expression([NotNull] TypescriptParser.Object_creation_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.object_creation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_creation_expression([NotNull] TypescriptParser.Object_creation_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypescriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] TypescriptParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypescriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] TypescriptParser.IdentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
