//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TypescriptParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TypescriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ITypescriptParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_unit([NotNull] TypescriptParser.Compilation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.namespace_or_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_or_type_name([NotNull] TypescriptParser.Namespace_or_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] TypescriptParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.base_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_type([NotNull] TypescriptParser.Base_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.simple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type([NotNull] TypescriptParser.Simple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_type([NotNull] TypescriptParser.Numeric_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type([NotNull] TypescriptParser.Class_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument_list([NotNull] TypescriptParser.Type_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_list([NotNull] TypescriptParser.Argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] TypescriptParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] TypescriptParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.non_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_assignment_expression([NotNull] TypescriptParser.Non_assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] TypescriptParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] TypescriptParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] TypescriptParser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.conditional_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_or_expression([NotNull] TypescriptParser.Conditional_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.conditional_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_and_expression([NotNull] TypescriptParser.Conditional_and_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusive_or_expression([NotNull] TypescriptParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusive_or_expression([NotNull] TypescriptParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expression([NotNull] TypescriptParser.And_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality_expression([NotNull] TypescriptParser.Equality_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_expression([NotNull] TypescriptParser.Relational_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expression([NotNull] TypescriptParser.Shift_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive_expression([NotNull] TypescriptParser.Additive_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative_expression([NotNull] TypescriptParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] TypescriptParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] TypescriptParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] TypescriptParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simpleNameExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleNameExpression([NotNull] TypescriptParser.SimpleNameExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExpressions</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpressions([NotNull] TypescriptParser.ParenthesisExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalAccessExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralAccessExpression([NotNull] TypescriptParser.LiteralAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>thisReferenceExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThisReferenceExpression([NotNull] TypescriptParser.ThisReferenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>objectCreationExpression</c>
	/// labeled alternative in <see cref="TypescriptParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreationExpression([NotNull] TypescriptParser.ObjectCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_access([NotNull] TypescriptParser.Member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.bracket_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_expression([NotNull] TypescriptParser.Bracket_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_expression([NotNull] TypescriptParser.Lambda_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.anonymous_function_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_function_signature([NotNull] TypescriptParser.Anonymous_function_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.explicit_anonymous_function_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_anonymous_function_parameter_list([NotNull] TypescriptParser.Explicit_anonymous_function_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.explicit_anonymous_function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_anonymous_function_parameter([NotNull] TypescriptParser.Explicit_anonymous_function_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.implicit_anonymous_function_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicit_anonymous_function_parameter_list([NotNull] TypescriptParser.Implicit_anonymous_function_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.anonymous_function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_function_body([NotNull] TypescriptParser.Anonymous_function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declarationStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] TypescriptParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>embeddedStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbeddedStatement([NotNull] TypescriptParser.EmbeddedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbedded_statement([NotNull] TypescriptParser.Embedded_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>emptyStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] TypescriptParser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] TypescriptParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] TypescriptParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switchStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] TypescriptParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>whileStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] TypescriptParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>doStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStatement([NotNull] TypescriptParser.DoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] TypescriptParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>foreachStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStatement([NotNull] TypescriptParser.ForeachStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] TypescriptParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continueStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] TypescriptParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>returnStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] TypescriptParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>throwStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowStatement([NotNull] TypescriptParser.ThrowStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tryStatement</c>
	/// labeled alternative in <see cref="TypescriptParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryStatement([NotNull] TypescriptParser.TryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] TypescriptParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.local_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_declaration([NotNull] TypescriptParser.Local_variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.local_variable_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_type([NotNull] TypescriptParser.Local_variable_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.local_variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_declarator([NotNull] TypescriptParser.Local_variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.if_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_body([NotNull] TypescriptParser.If_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.switch_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_section([NotNull] TypescriptParser.Switch_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.switch_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_label([NotNull] TypescriptParser.Switch_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] TypescriptParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.for_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_initializer([NotNull] TypescriptParser.For_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.for_iterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_iterator([NotNull] TypescriptParser.For_iteratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.catch_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_clauses([NotNull] TypescriptParser.Catch_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.specific_catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecific_catch_clause([NotNull] TypescriptParser.Specific_catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.general_catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_catch_clause([NotNull] TypescriptParser.General_catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.finally_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinally_clause([NotNull] TypescriptParser.Finally_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.resource_acquisition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource_acquisition([NotNull] TypescriptParser.Resource_acquisitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.namespace_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_declaration([NotNull] TypescriptParser.Namespace_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.namespace_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_body([NotNull] TypescriptParser.Namespace_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.namespace_member_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_member_declarations([NotNull] TypescriptParser.Namespace_member_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.namespace_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_member_declaration([NotNull] TypescriptParser.Namespace_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_declaration([NotNull] TypescriptParser.Type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_list([NotNull] TypescriptParser.Type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter([NotNull] TypescriptParser.Type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_body([NotNull] TypescriptParser.Class_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.class_member_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member_declarations([NotNull] TypescriptParser.Class_member_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.class_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member_declaration([NotNull] TypescriptParser.Class_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.all_member_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_member_modifiers([NotNull] TypescriptParser.All_member_modifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.all_member_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_member_modifier([NotNull] TypescriptParser.All_member_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.common_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_member_declaration([NotNull] TypescriptParser.Common_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.typed_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTyped_member_declaration([NotNull] TypescriptParser.Typed_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.variable_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarators([NotNull] TypescriptParser.Variable_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarator([NotNull] TypescriptParser.Variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initializer([NotNull] TypescriptParser.Variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_type([NotNull] TypescriptParser.Return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_name([NotNull] TypescriptParser.Member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.method_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_body([NotNull] TypescriptParser.Method_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter_list([NotNull] TypescriptParser.Formal_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.fixed_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_parameters([NotNull] TypescriptParser.Fixed_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.fixed_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_parameter([NotNull] TypescriptParser.Fixed_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.constructor_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_initializer([NotNull] TypescriptParser.Constructor_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] TypescriptParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.variant_type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_type_parameter_list([NotNull] TypescriptParser.Variant_type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.variant_type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_type_parameter([NotNull] TypescriptParser.Variant_type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.enum_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_body([NotNull] TypescriptParser.Enum_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.enum_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_member_declaration([NotNull] TypescriptParser.Enum_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.right_arrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_arrow([NotNull] TypescriptParser.Right_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.right_shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift([NotNull] TypescriptParser.Right_shiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.right_shift_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift_assignment([NotNull] TypescriptParser.Right_shift_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] TypescriptParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] TypescriptParser.Boolean_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] TypescriptParser.String_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_definition([NotNull] TypescriptParser.Class_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.enum_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_definition([NotNull] TypescriptParser.Enum_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.field_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_declaration([NotNull] TypescriptParser.Field_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.constructor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_declaration([NotNull] TypescriptParser.Constructor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_declaration([NotNull] TypescriptParser.Method_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.method_member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_member_name([NotNull] TypescriptParser.Method_member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.arg_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg_declaration([NotNull] TypescriptParser.Arg_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.method_invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_invocation([NotNull] TypescriptParser.Method_invocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.object_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_creation_expression([NotNull] TypescriptParser.Object_creation_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TypescriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] TypescriptParser.IdentifierContext context);
}
